# -*- coding: utf-8 -*-
{
    'name': 'HEALTH INSURANCE ',
    'version': '1.0',
    'summary': '--',
    'sequence': 26,
    'description': """
    'author': 'Eda Şahinli',

    """,
    'category': 'Health Insurance',
    'depends': ['base', 'base_environment', 'hr_employee_ext', 'web_notify', 'approval_dashboard'],

    'data': [
        'security/res_groups.xml',
        'security/security_rule.xml',
        'security/ir.model.access.csv',
        'views/cover_period.xml',
        'data/ir_cron_data.xml',
        'data/mail_templates.xml',
        'data/request_sequence.xml',
        'data/attachment_type.xml',
        'data/tier_definitions.xml',
        'wizard/ac_health_insurance_excel_wizard_views.xml',
        'wizard/ac_health_insurance_report_wizard_views.xml',
        'views/ac_health_insurance_sms.xml',
        'views/health_insurance_exception.xml',
        'views/cover_definition.xml',
        'views/cover_period_definition.xml',
        'views/health_insurance.xml',
        'views/configuration.xml',
        'views/health_insurance_report.xml',
        'views/health_insurance_cancelled_record.xml',
        'views/health_insurance_summary.xml',
        'views/health_insurance_general_users.xml',
        'views/health_insurance_secretary_users.xml',
        'views/health_insurance_special_assistant.xml',
        'views/personal_department_permission.xml',
        'views/health_insurance_attachment.xml',
        'views/health_insurance_reminder_opr_history.xml',
        'views/ac_health_insurance_kvkk_data.xml',
        'views/ac_health_insurance_woking_type.xml',
        'views/assets_backend.xml',
        'views/menu_health_insurance.xml',
    ],
    'demo': [

    ],
    'qweb': [
        'static/src/qweb/lock_period.xml',
        'static/src/qweb/open_lock_period.xml',
        'static/src/qweb/add_summary.xml',
        'static/src/qweb/add_payroll.xml',
        'static/src/qweb/discard_opr.xml',
        'static/src/qweb/send_reminder_mail.xml',
        'static/src/qweb/send_sms.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
