# -*- coding: utf-8 -*-
{
    'name': "Education Management",
    'summary': """ Planning, Courses & Activities ! """,
    'description': """Follow your learning status from HUMA""",
    'author': """TAI""",
    'website': """https://www.tai.com.tr/""",
    'category': 'hr',
    'version': '0.1',
    'depends': [
        # 'base',
        # 'web',
        # 'hr_employee_ext',
        # 'project',
        # 'facility_management',
        # 'cool_admin_odoo',
        # 'mail',
        # 'base_environment',
        'approval_dashboard',
        'hr_severance',
        'mail_activity_ext',
        'notification_management'
    ],
    # "external_dependencies": {'python': ['unicode_tr']},
    'qweb': [
        'static/src/xml/academy_dashboard_template.xml',
        'static/src/xml/ed_learning_poll.xml',
        'static/src/xml/read_information.xml',
        'static/src/xml/change_state.xml',
    ],
    'data': [
        'sequence/academy_sequence.xml',
        'security/groups.xml',
        'security/trainer_groups.xml',
        'security/ir.model.access.csv',
        'data/renewal_status_type.xml',
        'views/course/ttc/ttc_course_view.xml',
        'views/course/ttc/ttc_all_course_view.xml',
        'views/course/ttc/ttc_elearning_course_view.xml',
        'views/course/ttc/course_learning_objectives.xml',
        'views/course/ttc/ttc_requests_view.xml',
        'views/course/ttc/ttc_elearning_requests_view.xml',
        'views/course/ttc/course_category_view.xml',
        'views/course/ttc/course_document.xml',
        'views/course/tan/tan_external_view.xml',
        'views/course/tan/tan_all_view.xml',
        'views/course/tan/tan_internal_view.xml',
        'views/course/tan/tan_knowledge_view.xml',
        'views/course/tan/tan_category_view.xml',
        'views/course/tan/ojt_view.xml',
        'views/course/tan/ojt_report_view.xml',
        'views/course/tan/tan_document.xml',
        'views/course/pst/pst_course_view.xml',
        'views/course/poll_attachment_view.xml',
        'views/course/poll_view.xml',
        'views/course/hr_employee_ext_courses_view.xml',
        'views/course/common/document.xml',
        'views/training/training_program_view.xml',
        'views/training/training_method_view.xml',
        'views/definitions/classroom_view.xml',
        'views/course/pst/classroom_view.xml',
        'views/definitions/classroom_type_view.xml',
        'views/definitions/competency.xml',
        'views/definitions/confidentiality_level.xml',
        'views/definitions/duration_type_view.xml',
        'views/definitions/duration_view.xml',
        'views/definitions/source_system_view.xml',
        'views/definitions/exam_style_view.xml',
        'views/definitions/exam_type_view.xml',
        'views/definitions/renewal_status_type.xml',
        'views/definitions/workorder_view.xml',
        'views/definitions/course_topic_view.xml',
        'views/definitions/course_keyword_view.xml',
        'views/definitions/new_course_type.xml',
        'views/definitions/trainer_view.xml',
        'views/definitions/content_category.xml',
        'views/planning/planning_instructors.xml',
        'views/dashboard/dashboard_action.xml',
        'views/dashboard/dashboard_assets.xml',
        'views/planning/planning_ttc_view.xml',
        'views/planning/planning_payment.xml',
        'views/planning/planning_ojt_view.xml',
        'views/planning/planning_pst_view.xml',
        'views/planning/planning_ttc_elearning_view.xml',
        'views/planning/planning_tan_knw_view.xml',
        'views/planning/planning_tan_ext_view.xml',
        'views/planning/planning_tan_int_view.xml',
        'views/planning/planning_shift_view.xml',
        'views/planning/planning_shift_block_view.xml',
        'views/planning/planning_block_view.xml',
        'views/planning/my_planning_calendar_view.xml',
        'views/planning/my_trainer_planning_calendar_view.xml',
        'views/planning/my_scheduler_course_view.xml',
        'views/planning/planning_search.xml',
        'views/planning/ed_learning_service_log.xml',
        'views/announcement/announcement_view.xml',
        'views/announcement/announcement_mail_view.xml',
        'views/announcement/ed_learning_activity.xml',
        'views/demand/demand_view.xml',
        'views/demand/tan_poll_view.xml',
        'views/demand/demand_document_view.xml',
        'views/demand/queue_demand_completed_view.xml',
        'views/demand/success_demand_view.xml',
        'views/demand/demand_temporal_view.xml',
        'views/demand/ed_learning_same_demand.xml',
        'views/data_fix/data_fix.xml',
        'views/atlas_reqs.xml',
        'wizards/views/planning_block_wizard_view.xml',
        'wizards/views/group_demand_wizard_view.xml',
        'wizards/views/export_demand_wizard_view.xml',
        'wizards/views/vendor_wizard_view.xml',
        'wizards/views/manager_bulk_planing.xml',
        'wizards/views/all_demand.xml',
        'wizards/views/renewal_status_update.xml',
        'wizards/views/recert_date_update.xml',
        'wizards/views/classroom_reservation.xml',
        'wizards/views/create_recert_demand.xml',
        'wizards/views/create_recert_pst_demand.xml',
        'wizards/views/change_state.xml',
        'wizards/views/employee_taken_courses.xml',
        'wizards/views/automatic_planning.xml',
        'views/menu/menu.xml',
        'views/menu/menu_pst.xml',
        "data/tier_validation_mail_template.xml",
        "data/plan_mails/plan_assign_participant_mail_template.xml",
        "data/plan_mails/isg_parent_id_manuel_mail_template.xml",
        "data/plan_mails/firstaid_manuel_mail_template.xml",
        "data/create_automatic_plan.xml",
        "data/plan_mails/plan_assign_participant_change_mail_template.xml",
        "data/plan_mails/plan_assign_participant_partial_mail_template.xml",
        "data/plan_mails/plan_cancel_participant_partial_mail_template.xml",
        "data/plan_mails/plan_assign_trainer_partial_mail_template.xml",
        "data/plan_mails/plan_assign_trainer_mail_template.xml",
        "data/plan_mails/plan_assign_parent_mail_template.xml",
        "data/plan_mails/plan_assign_reminder_parent_mail_template.xml",
        "data/plan_mails/plan_assign_reminder_participant_mail_template.xml",
        "data/plan_mails/plan_assign_tomorrow_mail_template.xml",
        "data/plan_mails/plan_reminder_manager.xml",
        "data/plan_mails/plan_poll_status_reminder.xml",
        "data/activity_cron/trainer_activity.xml",
        "data/ttc_request_tier_definition.xml",
        "data/ttc_course_tier_definition.xml",
        "data/tan_knowledge_sharing_tier.xml",
        "data/hr_severance_resignation_instructor_mail.xml",
        "data/instructor_announcement_mail_template.xml",
        "data/tp_tier_definition.xml",
        "data/ojt_tier_definition.xml",
        "data/demand_tier_definition.xml",
        "data/activity_type_data.xml",
        "data/log_config.xml",
        "data/reports.xml",

        "data/ir_cron_data.xml",
        "data/ed_learning_competence_data.xml",
        "data/trainer_sms_cron.xml",

    ],
    'installable': True,
    'application': True,

}
