{
    'name': 'Turkish Aerospace Leaves',
    'summary': 'Personel İzin Giriş ve Takip Sistemi ',
    'category': 'Human Resources',
    'website': 'https://www.odoo.com/page/leaves',
    'author': 'Ekip-2',
    'version': '0.1',
    'depends': ['hr_employee_ext', 'hr_holidays', 'base_tier_validation_ext', 'approval_dashboard','resource_ext', 'hr_overtime'],
    'data': [
        'data/mail_templates.xml',
        'data/set_missing_hours_cron.xml',
        'data/flexible_employee_leaves_data_cron.xml',
        'data/hr_leave_authorization_date_data.xml',
        'data/administrative_leave_cron.xml',
        'data/close_monthly_leave_cron.xml',
        'data/new_rc_create_for_auto.xml',
        'views/assets_backend.xml',
        'views/hr_leave_authorization_date.xml',
        'views/hr_leave_manager_views.xml',
        'views/hr_leave_ik_views.xml',
        'views/hr_leave_pers_views.xml',
        'views/custom_ik_pers_views.xml',
        'views/hr_leave_type_views.xml',
        'views/hr_leave_transfer_views.xml',
        'views/hr_leave_file_template_views.xml',
        'views/hr_leave_annual_right_views.xml',
        'views/hr_group_leaves_views.xml',
        'views/hr_leave_close_monthly_auto.xml',
        'views/hr_group_leaves_batch_views.xml',
        'views/hr_leave_remaining_views.xml',
        'views/state_change_restriction.xml',
        'views/hr_leave_all_leaves_views.xml',
        'wizard/hr_leave_pdks_wizard_views.xml',
        'wizard/hr_leave_transfer_wizard_views.xml',
        'wizard/hr_leave_read_excel_wizard_views.xml',
        'wizard/hr_leave_delete_excel_wizard_views.xml',
        'wizard/attendance_summary_inherit_views.xml',
        'wizard/call_leave_methods_views.xml',
        'wizard/overtime_leave_right_upload.xml',
        'wizard/reflect_leaves_views.xml',
        'wizard/missing_leave_wizard_views.xml',
        'security/hr_holidays_security.xml',
        'security/tier_admin_group.xml',
        'security/sms_group.xml',
        'security/reversible_group.xml',
        'security/new_three_group.xml',
        'security/ir.model.access.csv',
        'views/hr_leave_menu.xml',
        'data/ir_cron_data.xml',
        'data/create_missing_resource_calendar_cron.xml',
        'data/new_miss_leave_cr.xml',
        'data/hour_leaves_auto_cron.xml',
        'data/hour_leaves_auto_month_cron.xml',
        'data/hour_leaves_auto_daily.xml',
        'data/record_bulk_leave_cron.xml',
        'data/record_medical_leave_cron.xml',
        'data/record_bulk_daily_cron.xml',
    ],
    'qweb': [
        'static/src/qweb/show_pdks.xml',
        'static/src/qweb/remove_save.xml',
    ],

    'installable': True,
    'application': True,
}
