{
    'name': 'Turkish Aerospace Overtime ',
    'summary': 'Overtime Approval Module',
    'category': 'Human Resources ',
    'website': 'https://www.odoo.com/page/overtime',
    'author': 'Ekip-2',
    'version': '0.1',
    'depends': ['hr_employee_ext', 'hr_department_ext', 'approval_dashboard', 'resource_ext',
                'notification_management'],
    'data': [
        'security/hr_overtime_security.xml',
        'security/new_group.xml',
        'security/food_group.xml',
        'security/tier_admin_group.xml',
        'security/tier_reversible_group.xml',
        'security/service_and_food_report.xml',
        'security/ir.model.access.csv',
        'data/report_paperformat.xml',
        'data/cron.xml',
        'data/new_cron_up_paid.xml',
        'data/activity_type_data.xml',
        'data/overtime_amount_up_cron.xml',
        'data/decimal_params_data.xml',
        'views/assets_backend.xml',
        'views/hr_par_overtime_type.xml',
        'views/hr_overtime_realized.xml',
        'views/hr_par_overtime_reason.xml',
        'views/hr_overtime_request.xml',
        'views/hr_overtime_collective_request.xml',
        'views/hr_overtime_service.xml',
        'views/hr_overtime_food.xml',
        'views/hr_overtime_food_information.xml',
        'views/hr_overtime_manager_views.xml',
        'views/hr_overtime_manager_approved_views.xml',
        'views/hr_overtime_building_rel.xml',
        'views/hr_overtime_leave_right.xml',
        'views/mail_templates.xml',
        'views/hr_overtime_deadline.xml',
        'wizard/hr_overtime_bus_report.xml',
        'wizard/hr_overtime_bus_report_template.xml',
        'wizard/hr_overtime_approve_wizard_views.xml',
        'wizard/overtime_chief_screen.xml',
        'wizard/sh_detail_used_log_views.xml',
        'wizard/hr_overtime_food_report.xml',
        'wizard/hr_overtime_food_report_template.xml',
        'wizard/summary_wizard_inherit.xml',
        'wizard/hr_overtime_bus_daily_excel_report.xml',
        'wizard/detail_of_paid_amount_views.xml',
        'views/external_moves.xml',
        'views/hr_overtime_menu.xml'
    ],
    'qweb': [
        'static/src/qweb/remove_save.xml',
        'static/src/qweb/approve_overtime.xml',
    ],
    'qweb': ['static/src/xml/*.xml'],
    'installable': True,
    'application': True,

}
