{
    'name': 'Turkish Aerospace Shift Plan',
    'summary': 'Shift Plan Module',
    'category': 'HR',
    'website': 'https://www.odoo.com/page/shiftplan',
    'author': 'Ekip-2',
    'version': '0.1',
    'depends': ['hr_employee_ext', 'base_environment', 'web_widget_x2many_2d_matrix', 'notification_management'],
    'qweb': [
        'static/src/xml/hr_shift_plan_enterance_view_template.xml',
    ],
    'data': [
        'views/hr_shift_plan_matrix.xml',
        'views/hr_shift_plan.xml',
        'views/hr_shift_plan_managers_domain.xml',
        'views/hr_shift_plan_collective.xml',
        'views/hr_shift_plan_task_center.xml',
        'views/hr_shift_plan_term.xml',
        'views/hr_shift_plan_flexible.xml',
        'views/excel_im_definition_views.xml',
        'views/hr_shift_plan_bulk_flex.xml',
        'wizard/hr_shift_plan_excel_views.xml',
        'wizard/hr_shift_plan_automatic_views.xml',
        'security/hr_shift_plan_security.xml',
        'security/group_manager_domain.xml',
        'security/ir.model.access.csv',
        'views/hr_shift_plan_menu.xml',
        'data/ir_cron_data.xml',
        'data/ir_cron_call_for_ed_l.xml',
        'data/activity_type_data.xml',
        'views/enterance_action.xml',
        'views/enterance_assets.xml',
    ],
    'installable': True,
    'application': True,
}
