{
    'name': 'Turkish Aerospace Severance',
    'summary': 'Employee Severance Module',
    'category': 'Human Resources',
    'website': '',
    'author': 'Ekip-2',
    'version': '0.1',
    'depends': ['hr_employee_ext', 'hr_department_ext', 'approval_dashboard', 'hr_holidays_ext', 'notification_management','survey', 'ac_health_insurance'],
    'data': [
        'security/hr_severance_security.xml',
        'security/hr_severance_security_role.xml',
        'security/access_rule.xml',
        'security/business_partner.xml',
        'security/severance_new_group.xml',
        'security/activity_and_flow_role.xml',
        'security/ir.model.access.csv',
        'views/hr_resignation_notice.xml',
        'views/hr_resignation_review_activity.xml',
        'views/hr_resignation_notice_all.xml',
        'views/hr_resignation_notice_approve.xml',
        'views/hr_severance_request.xml',
        'views/hr_severance_request_approve.xml',
        'views/hr_severance_request_process.xml',
        'views/hr_severance_request_all.xml',
        'views/hr_par_notice_period.xml',
        'views/hr_severance_process.xml',
        'views/hr_resignation_notice_user.xml',
        'views/assets.xml',
        'views/activity_kanbans.xml',
        'views/activity_trees.xml',
        'data/report_paper_format.xml',
        #'data/survey_activity_type.xml',
        'data/only_manager_activity.xml',
        'data/hr_severance_process_data.xml',
        'views/hr_severance_request_report_template.xml',
        'views/hr_severance_report_for_bt.xml',
        'views/hr_severance_debt_information_report_template.xml',
        'reports/hr_severance_review_report.xml',
        'data/mail_templates.xml',
        'data/severance_activities.xml',
        'data/ir_cron_data.xml',
        'wizards/survey_popup.xml',
        # 'data/hr_severance_tier_data.xml',
        'views/hr_resignation_survey.xml',
        'views/hr_severance_menu.xml',

    ],
    'qweb': [
        'static/src/qweb/open_survey_button.xml',
        'static/src/js/*.xml',
    ],
    'installable': True,
    'application': True,
}
