# -*- coding: utf-8 -*-
{
    'name': "TUSAS Order Recording",
    'summary': """
        TUSAŞ Order Processing System""",
    'description': """
        TUSAS order recording, batch recording and processing system 
    """,
    'author': "Ekip",
    'website': "https://erp.tai.com.tr",
    'category': 'Human Resources',
    'version': '0.1',
    'depends': ['base', 'hr', 'hr_employee_ext', 'notification_management'],
    'data': [
        'security/hr_workorder_security.xml',
        'security/technopark_groups.xml',
        'security/access_rule.xml',
        'security/work_order_edit_rules.xml',
        'security/ir.model.access.csv',
        # 'views/project.xml',
        'views/assets_backend.xml',
        # 'views/wo_recording.xml',
        'data/activity_type_data.xml',
        'data/ir_cron.xml',
        'data/hours_sep_cron.xml',
        'data/update_final_date_cron.xml',
        'data/ir_config_db2_switch.xml',
        'views/wo_edit.xml',
        'views/wo_soir_qar_recording.xml',
        'views/collective_soir_recording.xml',
        'views/wo_order_type.xml',
        'views/wo_collective_definition.xml',
        'views/wo_allowed_department.xml',
        'views/wo_allowed_employee.xml',
        'views/wo_enterance_action.xml',
        'views/wo_enterance_assets.xml',
        'views/workmanship_definitions.xml',
        'views/wo_underwork.xml',
        'views/wo_technopark_daily.xml',
        'views/work_order_closing.xml',
        'wizard/hr_workorder_in_out_information.xml',
        'wizard/collective_underwork.xml',
        'wizard/monthly_calculation_score.xml',
        'wizard/wo_excel_upload_views.xml',
        'wizard/test_wizard.xml',
        'wizard/wo_calc_sample.xml',
        'wizard/upload_key_department_excel.xml',
        'views/wo_menu.xml',
    ],
    'qweb': [
        'static/src/qweb/show_in_out_information.xml',
        'static/src/qweb/view_tree.xml',
        'static/src/xml/wo_enterance_view_template.xml',
        'static/src/xml/missing_workorder.xml',
        'static/src/qweb/collective_underwork_button.xml',
    ],
    'installable': True,
    'application': True,

}
