# -*- coding: utf-8 -*-
{
    'name': "Approvals Dashboard",
    'summary': """ A cool Dashboard for Approvals """,
    'description': """Follow your approvals via this Dashboard """,
    'author': """TAI""",
    'website': """https://www.tai.com.tr/""",
    'category': 'general',
    'version': '0.1',
    'depends': ['base', 'web', 'base_tier_validation_ext', 'cool_admin_odoo'],
    'external_dependencies': {'python': ['zeep']},
    'qweb': [
        'static/src/xml/approvals_dashboard_template.xml',
        'static/src/xml/waiting_approvals_dashboard_template.xml',
        'static/src/xml/approved_approvals_dashboard_template.xml',
        'static/src/xml/rejected_approvals_dashboard_template.xml',
        'static/src/xml/requested_waiting_approvals_dashboard_template.xml',
        'static/src/xml/requested_approved_approvals_dashboard_template.xml',
        'static/src/xml/requested_rejected_approvals_dashboard_template.xml',
        'static/src/xml/refresh_button.xml',
        'static/src/xml/waiting_activities_dashboard_template.xml',
        'static/src/xml/done_activities_dashboard_template.xml',
        # 'static/src/xml/refresh_list_view_button.xml',
        'static/src/qweb/go_to_module_button.xml',
    ],
    'data': [
        'views/dashboard_action.xml',
        'views/dashboard_assets.xml',
        'views/icon_param_editing_views.xml',
        'views/approval_model_name.xml',
        'wizards/views/legacy_review_view.xml',
        'wizards/views/legacy_review_detail_view.xml',
        'wizards/views/popup_view.xml',
        'data/log_config.xml',
        'data/ir_cron.xml',
        'security/security.xml',
        'security/ir.model.access.csv',
    ],
    'installable': True,
    'application': True,
}
