{
    'name': 'Competence',
    'summary': 'Competence',
    'category': 'Human Resources',
    'website': 'https://www.odoo.com/page/competence',
    'author': 'Ekip-5',
    'version': '0.1',
    'depends': ["mail", 'hr_employee_ext', 'hr_employee_pan', "approval_dashboard", "crnd_web_list_popover_widget", "ed_learning",
                "hr_department_ext", "mail_activity_ext"],
    'data': [
        'security/res_groups.xml',
        'security/ir.model.access.csv',
        'security/rules.xml',
        'data/mail_template.xml',
        'data/ir_cron_data.xml',
        'data/ir_cron_data_extra.xml',
        'data/tier_definitions.xml',
        'data/hr_par_competence_role_category_type.xml',
        'data/hr_par_competence_duty_type.xml',
        'data/hr_par_competence_grade_type.xml',
        'data/hr_par_competence_evaluation_type.xml',
        'data/hr_par_competence_requirement_type.xml',
        'data/hr_par_competence_role_type.xml',
        'data/hr_competence_grade.xml',
        'data/hr_par_competence_role_competence_relation_type.xml',
        'data/hr_par_competence_competence_state_type.xml',
        'data/activity_type_data.xml',
        'data/ir_config_parameter_data.xml',
        'data/request_sequence.xml',
        'data/hr_par_competence_competence_category_type.xml',
        'views/assets_backend.xml',
        'views/hr_competence_mail_activity.xml',
        'views/hr_competence_editable_job_level.xml',
        'views/hr_competence_notification.xml',
        'views/hr_competence_competence.xml',
        'views/hr_competence_competence_demand.xml',
        'views/hr_competence_grade.xml',
        'views/hr_competence_role_competence_rel.xml',
        'views/hr_competence_role_competence_rel_demand.xml',
        'views/hr_competence_role.xml',
        'views/hr_competence_role_demand.xml',
        'views/hr_competence_requirements.xml',
        'views/hr_competence_requirements_demand.xml',
        'views/hr_competence_employee_requirements.xml',
        'views/hr_competence_employee_role.xml',
        'views/hr_competence_employee_role.xml',
        'views/hr_competence_competence_approve.xml',
        'views/hr_competence_competence_approve_evaluation.xml',
        'views/hr_competence_education_constraint.xml',
        'views/hr_competence_employee_job_title_constraint.xml',
        'views/hr_competence_reports.xml',
        'views/par_views/hr_par_competence_duty_type.xml',
        'views/par_views/hr_par_competence_evaluation_type.xml',
        'views/par_views/hr_par_competence_grade_type.xml',
        'views/par_views/hr_par_competence_requirement_type.xml',
        'views/par_views/hr_par_competence_competence_category_type.xml',
        'views/par_views/hr_par_competence_role_category_type.xml',
        'views/par_views/hr_par_competence_role_competence_relation_type.xml',
        'views/par_views/hr_par_competence_role_type.xml',
        'views/par_views/hr_par_competence_competence_state_type.xml',
        'views/hr_competence_employee_work_logbook.xml',
        'views/hr_competence_competence_approve_question.xml',
        'views/hr_competence_employee_duty.xml',
        'views/hr_competence_employee_duty_education.xml',
        'views/hr_competence_employee_duty_work_station.xml',
        'views/hr_competence_role_change_operations.xml',
        'views/hr_competence_competence_change_operations.xml',
        'views/hr_competence_user_views.xml',
        'views/hr_competence_academy_course.xml',
        'views/hr_competence_errors.xml',
        'views/hr_competence_planning.xml',
        'views/hr_competence_employee_rolecompetence_req_reports.xml',
        'views/hr_competence_employee_role_competence_old_system_history.xml',
        'views/hr_competence_old_system_approve_history.xml',
        'views/hr_competence_grade_updatable_jobs.xml',
        'views/hr_competence_academy_control.xml',
        'views/hr_competence_academy.xml',
        'views/hr_competence_unassign_records.xml',
        'views/ed_learning.xml',
        'views/hr_competence_ed_learning_complete_queue.xml',
        'wizards/views/hr_competence_employee_dismiss_competence.xml',
        'wizards/views/hr_competence_competence_demand_wizard.xml',
        'wizards/views/hr_competence_assign_role_wizard.xml',
        'wizards/views/hr_competence_role_demand_wizard.xml',
        'wizards/views/hr_competence_update_employee.xml',
        'wizards/views/bulk_update_wizard.xml',
        'wizards/views/hr_competence_compare_competence.xml',
        'wizards/views/educations.xml',
        'wizards/views/hr_competence_compare_role.xml',
        'wizards/views/assign_role_check_critical_role.xml',
        'wizards/views/role_competence_final_target.xml',
        'wizards/views/hr_competence_employee_duty_wizard.xml',
        'wizards/views/hr_competence_academy_services_wizard.xml',
        'wizards/views/hr_competence_workstation_services_wizard.xml',
        'wizards/views/role_competence_reports_wizard.xml',
        'wizards/views/employee_role_competence_req_reports_wizard.xml',
        'wizards/views/message_popup.xml',
        'wizards/views/assign_role_mail_wizard.xml',
        'wizards/views/competence_history_wizard.xml',
        'wizards/views/employee_role_competence_wizard.xml',
        'wizards/views/hr_competence_approve_evaluation_wizard.xml',
        'views/hr_competence_employee_excel.xml',
        'views/hr_competence_employee_excel_list.xml',
        'views/hr_competence_grade_change_request.xml',
        'views/hr_competence_menu.xml',
        'reports/paper_format.xml',
        'reports/hr_competence_role.xml',
        'reports/hr_competence_role_demand.xml',
        'reports/hr_competence_competence.xml',
        'reports/hr_competence_competence_demand.xml',
    ],
    'qweb': [
        'static/src/xml/hr_competence_entrance_view.xml',
        'static/src/qweb/change_role.xml',
        'static/src/qweb/change_competence.xml',
        'static/src/qweb/close_screen.xml',
        'static/src/qweb/done_selected_activity.xml',
        'static/src/qweb/done_selected_records.xml',
        'static/src/qweb/execute_set_role_opr.xml',
    ],

    'installable': True,
    'application': True,

}
